CREATE TABLE IF NOT EXISTS quotly_message (
    stanzaId VARCHAR(255) PRIMARY KEY NOT NULL,
    chatId VARCHAR(255) NOT NULL,
    fileId VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(chatId, fileId) REFERENCES quotly(chatId, fileId) ON DELETE CASCADE
);
