name: tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.github/workflows/forgejo-pr-sync.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.github/workflows/forgejo-pr-sync.yml'
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg webp

      - name: Run tests
        run: go test ./...
